entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        options: default

providers:
  file:
    directory: "/etc/traefik/conf.d/"
    watch: true

api:
  dashboard: true
  insecure: true

log:
  filePath: /etc/traefik/logstraefik.log
  format: json
  level: INFO

accessLog:
  filePath: /etc/traefik/log/traefik-access.log
  format: json
  filters:
    statusCodes:
      - "200"
      - "400-599"
    retryAttempts: true
    minDuration: "10ms"
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
