name: qbittorrent

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=Europe/Helsinki
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /srv/qbitorrent/config:/config
      - /mnt/media/qbittorrent/downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
