name: sonarr

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=Europe/Helsinki
    volumes:
      - /srv/sonarr/config:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
