services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:6cdf4fe-tensorrt
    shm_size: "256mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/frigate/config:/config
      - /mnt/nvr/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "192.168.10.6:8971:8971" # API and web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" # go2rtc
      - "192.168.10.6:5000:5000" # Unauthenticated API for integrating services, firewalled carefully
    environment:
      FRIGATE_TERRARIUM_CAM_IP: ${FRIGATE_TERRARIUM_CAM_IP}
      FRIGATE_HTTP_USERNAME: ${FRIGATE_HTTP_USERNAME}
      FRIGATE_HTTP_PASSWORD: ${FRIGATE_HTTP_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"

      # main route
      - "traefik.http.routers.frigate.rule=Host(`frigate.ottos.party`)"
      - "traefik.http.routers.frigate.entrypoints=lan-https, cf-tunnel"
      - "traefik.http.routers.frigate.middlewares=cloudflarewarp@file, authentik-forward-auth@file, proxy-secret@file"
      - "traefik.http.services.frigate.loadbalancer.server.port=8971"

      # aliases route
      - "traefik.http.routers.frigate-aliases.rule=Host(`nvr.ottos.party`)"
      - "traefik.http.routers.frigate-aliases.entrypoints=lan-https, cf-tunnel"
      - "traefik.http.routers.frigate-aliases.middlewares=cloudflarewarp@file, frigate-alias-redirect"
      - "traefik.http.routers.frigate-aliases.service=noop@internal"

      # alias redirect middleware
      - "traefik.http.middlewares.frigate-alias-redirect.redirectregex.regex=^.*\\.ottos\\.party(.*)$"
      - "traefik.http.middlewares.frigate-alias-redirect.redirectregex.replacement=https://frigate.ottos.party$1"
      - "traefik.http.middlewares.frigate-alias-redirect.redirectregex.permanent=true"

  frigate-timelapse-hls:
    image: 0x464e/frigate-timelapse-hls
    container_name: frigate-timelapse-hls
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "192.168.10.6:6773:6773"
    environment:
      FTHLS_APP_TIMEZONE: Europe/Helsinki
      FTHLS_APP_READY_BUFFER_SECONDS: "30"
      FTHLS_APP_LOG_LEVEL: DEBUG
      FTHLS_APP_RESTART_POLICY: resume
      FTHLS_CAMERA_NAME: terrarium
      FTHLS_FRIGATE_BASE_URL: http://frigate:5000
      FTHLS_FRIGATE_RECORDINGS_ROOT: /media/frigate/recordings
      FTHLS_TIMELAPSE_TIMELAPSE_SPEED: "288.0"
      FTHLS_TIMELAPSE_OUTPUT_FPS: "60"
      FTHLS_TIMELAPSE_HLS_SEGMENT_SECONDS: "2"
      FTHLS_FFMPEG_BINARY: ffmpeg
      FTHLS_FFMPEG_VIDEO_CODEC: h264_nvenc
      FTHLS_FFMPEG_PRESET: p2
      FTHLS_FFMPEG_PROFILE: main
      FTHLS_FFMPEG_CUSTOM_INPUT_ARGS: -hwaccel cuda -hwaccel_output_format cuda
    volumes:
      - /mnt/nvr/frigate/storage/recordings:/recordings:ro
      - /mnt/nvr/frigate/storage/timelapses:/output
      - /srv/frigate-timelapse-hls/data:/data

    labels:
      - "traefik.enable=true"

      # main route
      - "traefik.http.routers.frigate-timelapse-hls.rule=Host(`timelapse.frigate.ottos.party`)"
      - "traefik.http.routers.frigate-timelapse-hls.entrypoints=lan-https, cf-tunnel"
      - "traefik.http.routers.frigate-timelapse-hls.middlewares=cloudflarewarp@file, authentik-forward-auth@file"

      # aliases route
      - "traefik.http.routers.frigate-timelapse-hls-aliases.rule=Host(`timelapse.nvr.ottos.party`)"
      - "traefik.http.routers.frigate-timelapse-hls-aliases.entrypoints=lan-https, cf-tunnel"
      - "traefik.http.routers.frigate-timelapse-hls-aliases.middlewares=cloudflarewarp@file, frigate-timelapse-hls-alias-redirect"
      - "traefik.http.routers.frigate-timelapse-hls-aliases.service=noop@internal"

      # alias redirect middleware
      - "traefik.http.middlewares.frigate-timelapse-hls-alias-redirect.redirectregex.regex=^.*\\.ottos\\.party(.*)$"
      - "traefik.http.middlewares.frigate-timelapse-hls-alias-redirect.redirectregex.replacement=https://timelapse.frigate.ottos.party$1"
      - "traefik.http.middlewares.frigate-timelapse-hls-alias-redirect.redirectregex.permanent=true"
