name: media

x-common-env: &common-env
  PUID: 2001
  PGID: 2001
  TZ: Europe/Helsinki


services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      <<: *common-env
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /srv/qbitorrent/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      <<: *common-env
    volumes:
      - /srv/sonarr/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "8989:8989"
    restart: unless-stopped


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      <<: *common-env
    volumes:
      - /srv/radarr/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "7878:7878"
    restart: unless-stopped


  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *common-env
    volumes:
      - /srv/jellyfin/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "8096:8096" # HTTP Web UI
      - "8920:8920" # HTTPS Web UI
      - "7359:7359/udp" # Autodiscovery on local network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
