name: media

x-common-env: &common-env
  PUID: 2001
  PGID: 2001
  TZ: Europe/Helsinki


services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      <<: *common-env
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /srv/qbitorrent/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "192.168.10.6:8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # main route
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.ottos.party`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

      # aliases route
      - "traefik.http.routers.qbittorrent-aliases.rule=HostRegexp(`qbt?\\.ottos\\.party`)"
      - "traefik.http.routers.qbittorrent-aliases.entrypoints=https"
      - "traefik.http.routers.qbittorrent-aliases.middlewares=qbittorrent-alias-redirect"
      - "traefik.http.routers.qbittorrent-aliases.service=noop@internal"

      # alias redirect middleware
      - "traefik.http.middlewares.qbittorrent-alias-redirect.redirectregex.regex=^.*\\.ottos\\.party(.*)$"
      - "traefik.http.middlewares.qbittorrent-alias-redirect.redirectregex.replacement=https://qbittorrent.ottos.party$1"
      - "traefik.http.middlewares.qbittorrent-alias-redirect.redirectregex.permanent=true"


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      <<: *common-env
    volumes:
      - /srv/sonarr/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "192.168.10.6:8989:8989"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.ottos.party`)"
      - "traefik.http.routers.sonarr.entrypoints=https"


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      <<: *common-env
    volumes:
      - /srv/radarr/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "7878:7878"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.ottos.party`)"
      - "traefik.http.routers.radarr.entrypoints=https"


  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *common-env
    volumes:
      - /srv/jellyfin/config:/config
      - /mnt/media:/mnt/media
    ports:
      - "192.168.10.6:8096:8096" # HTTP Web UI
      # - "8920:8920" # HTTPS Web UI
      - "7359:7359/udp" # Autodiscovery on local network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"

      # main route
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.ottos.party`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

      # aliases route
      - "traefik.http.routers.jellyfin-aliases.rule=Host(`jelly.ottos.party`)"
      - "traefik.http.routers.jellyfin-aliases.entrypoints=https"
      - "traefik.http.routers.jellyfin-aliases.middlewares=jellyfin-alias-redirect"
      - "traefik.http.routers.jellyfin-aliases.service=noop@internal"

      # alias redirect middleware
      - "traefik.http.middlewares.jellyfin-alias-redirect.redirectregex.regex=^.*\\.ottos\\.party(.*)$"
      - "traefik.http.middlewares.jellyfin-alias-redirect.redirectregex.replacement=https://jellyfin.ottos.party$1"
      - "traefik.http.middlewares.jellyfin-alias-redirect.redirectregex.permanent=true"
